"""empty message

Revision ID: 6f5dc5ed57f9
Revises: 
Create Date: 2018-08-03 12:52:38.076203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5dc5ed57f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    quiz = op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('response_time', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('dificulty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(quiz,
                   [
                       {'id': 1,
                        'name':'Teste de linux',
                        'response_time': '00:10:00',
                        'category':'linux',
                        'dificulty':'junior',
                        'password':'admin'},
                        {'id': 2,
                        'name':'Teste de windows',
                        'response_time': '00:10:00',
                        'category':'windows',
                        'dificulty':'pleno',
                        'password':'admin'}

                   ]
                   )

    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    op.bulk_insert(users,
                   [
                       {'id': 1,
                        'name':'Administrator',
                        'email': 'admin@challange.com.br',
                        'username':'admin',
                        'telefone':'1111111',
                        'password':'admin',
                        'admin':True},
                        {'id': 2,
                        'name':'User',
                        'email': 'user@challange.com.br',
                        'username':'user',
                        'telefone':'1111111',
                        'password':'user',
                        'admin':False}

                   ]
                   )

    questions_disserty = op.create_table('questions_disserty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(), nullable=False),
    sa.Column('right_question', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(questions_disserty,
                   [
                       {'id': 1,
                        'questions':'Como faco para desligar o windows (apenas comando sem variavel)',
                        'right_question': 'clica no botao',
                        'quiz_id':2}

                   ]
                   )

    questions_multiple = op.create_table('questions_multiple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option_1', sa.String(), nullable=False),
    sa.Column('option_2', sa.String(), nullable=False),
    sa.Column('option_3', sa.String(), nullable=False),
    sa.Column('option_4', sa.String(), nullable=False),
    sa.Column('right_question', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(questions_multiple,
                   [
                       {'id': 1,
                        'question':'Qual diretorio que contem os logs?',
                        'option_1':'/var/log',
                        'option_2':'/var/logs',
                        'option_3':'/etc/logs',
                        'option_4':'/etc/log',
                        'right_question':'A',
                        'quiz_id':1}

                   ]
                   )

    quiz_users = op.create_table('quiz_users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'quiz_id')
    )

    op.bulk_insert(quiz_users,
                   [
                       {'id': 1,
                        'users_id':1,
                        'quiz_id': 1},
                        {'id': 2,
                        'users_id':1,
                        'quiz_id': 2},
                        {'id': 3,
                        'users_id':2,
                        'quiz_id': 1},
                        {'id': 4,
                        'users_id':2,
                        'quiz_id': 2}

                   ]
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_users')
    op.drop_table('questions_multiple')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('quiz')
    # ### end Alembic commands ###
