"""Add table Users

Revision ID: 9c069e81679c
Revises: 
Create Date: 2018-07-24 11:35:39.785836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c069e81679c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(users,
                   [
                       {'id': 1,
                        'name':'Administrator',
                        'email': 'admin@challange.com.br',
                        'username':'admin',
                        'telefone':'1111111',
                        'password':'admin',
                        'admin':True},
                        {'id': 2,
                        'name':'User',
                        'email': 'user@challange.com.br',
                        'username':'user',
                        'telefone':'1111111',
                        'password':'user',
                        'admin':False}

                   ]
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
